name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Devvy
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Start Devvy with '...'
        2. Send message '...'
        3. Execute command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include any error messages or logs.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Affected
      description: Which part of Devvy is affected?
      options:
        - Agent (Coder/Critic/Debugger/Architect/End User)
        - CLI/Terminal UI
        - Configuration/Setup
        - Tool Execution (bash, file operations, etc.)
        - LLM Integration (API communication)
        - Conversation Management
        - Other/Unknown
    validations:
      required: true

  - type: input
    id: agent
    attributes:
      label: Specific Agent (if applicable)
      description: If the bug is agent-specific, which agent?
      placeholder: "e.g., Coder, Critic, Debugger, Architect, End User"

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider are you using?
      options:
        - OpenAI
        - Anthropic (Claude)
        - OpenRouter
        - Custom API
        - Not applicable
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      description: Which model are you using?
      placeholder: "e.g., gpt-4o, claude-3-5-sonnet-20241022, etc."

  - type: input
    id: version
    attributes:
      label: Devvy Version
      description: What version of Devvy are you using?
      placeholder: "Run 'devvy --version' or check package.json"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      description: Which runtime are you using?
      options:
        - Bun
        - Node.js
        - Unknown
    validations:
      required: true

  - type: input
    id: runtime-version
    attributes:
      label: Runtime Version
      description: Version of Bun/Node.js
      placeholder: "e.g., Bun 1.0.0, Node.js 18.0.0"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - macOS
        - Linux
        - Windows
        - WSL (Windows Subsystem for Linux)
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Output
      description: Please paste any relevant error messages, logs, or console output.
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, configuration details, etc.)
      placeholder: Add any other context here...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am willing to help test a fix for this bug if needed
          required: false
