name: 📚 Documentation Improvement
description: Suggest improvements to documentation, guides, or examples
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve Devvy's documentation! Whether it's fixing typos, clarifying confusing sections, or adding new guides.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What kind of documentation needs improvement?
      options:
        - README.md
        - Setup/Installation Instructions
        - Usage Examples
        - API/Configuration Reference
        - Agent Documentation (AGENTS.md)
        - Code Comments
        - New Guide/Tutorial Needed
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing Information
        - Incorrect/Outdated Information
        - Unclear/Confusing Explanation
        - Typo/Grammar
        - Broken Link
        - Missing Example
        - Need More Details
        - Needs Restructuring
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation that needs improvement?
      placeholder: "e.g., README.md line 45, Installation section, or 'Need new guide for...'"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say (if applicable)?
      placeholder: Quote the current text or describe what's currently there...
      render: markdown

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What's wrong or missing?
      placeholder: "The documentation doesn't explain... / The instructions are unclear because... / There's no example for..."
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: "It should explain... / Add an example showing... / Reword to say..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Proposed Example (if applicable)
      description: If you're suggesting a new example or code snippet, provide it here.
      placeholder: |
        ```bash
        # Example command
        devvy config set-model gpt-4o
        ```
      render: markdown

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit most from this documentation improvement?
      options:
        - New Users (First-time setup)
        - Intermediate Users (Regular usage)
        - Advanced Users (Configuration/Customization)
        - Contributors/Developers
        - All Users
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context that would help improve the documentation?
      placeholder: "I was trying to... / Common use case is... / This confused me because..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute this documentation improvement?
      options:
        - label: I would be willing to submit a PR with the documentation improvements
          required: false
        - label: I can help review documentation improvements
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have clearly described what needs to be improved and how
          required: true
